### ISSUE TITLE
Give warning while building due to incompatible assignment.

### ISSUE THREAD

**Issue by sourabhjains** [HewlettPackard/netperf#16]
https://github.com/HewlettPackard/netperf/blob/3ce554d014156e5eb0453526a1a7c6a0001420ac/src/netserver.c#L264

**Comment by marceloleitner** [comment]
@grundlerchromium

**Comment by grundlerchromium** [comment]
Sorry - I didn't see this issue until Marcelo added me directly or I would have posted a fix.

@ChrisLynchHPE   : qsn posted a pull request which fixes it:
https://github.com/HewlettPackard/netperf/pull/21
