### ISSUE TITLE
Fail to compile netserver.c on Linux

### ISSUE THREAD

**Issue by jijianwen** [HewlettPackard/netperf#17]
I got the following error message when compiling it on RHEL7.4, please help check:
gcc -DHAVE_CONFIG_H -I. -I..      -MT netserver.o -MD -MP -MF .deps/netserver.Tpo -c -o netserver.o netserver.c
netserver.c: In function ‘open_debug_file’:
netserver.c:259:14: error: incompatible types when assigning to type ‘char[4096]’ from type ‘char *’
     FileName = NETPERF_NULL;
              ^
netserver.c:260:19: error: ‘Filename’ undeclared (first use in this function)
     where = fopen(Filename, "w");

**Comment by grundlerchromium** [comment]
Sorry, the HP team needs to pick up this pull request in order to fix this
build failure:
    https://github.com/HewlettPackard/netperf/pull/11

cheers,
grant

**Comment by IncredibleAaron** [comment]
Same story here. netserver.c cannot properly compile. 
OS version:  **centos-release-7-4.1708.el7.centos.x86_64**
Kernel: **Linux 3.10.0-693.21.1.el7.x86_64**

Error as below:
`netserver.c: In function ‘open_debug_file’:
netserver.c:259:14: error: incompatible types when assigning to type ‘char[4096]’ from type ‘char *’
     FileName = NETPERF_NULL;
              ^
netserver.c:260:19: error: ‘Filename’ undeclared (first use in this function)
     where = fopen(Filename, "w");
                   ^
netserver.c:260:19: note: each undeclared identifier is reported only once for each function it appears in
netserver.c:264:11: warning: assignment makes pointer from integer without a cast [enabled by default]
     where = mkstemp(FileName);
           ^
make[2]: *** [netserver.o] Error 1
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1
`

**Comment by marceloleitner** [comment]
We can close this now, right?

**Comment by grundlerchromium** [comment]
Yes. I'm not familiar with how to manage issues in github. Can only @jijianwen close this?

**Comment by grundlerchromium** [comment]
@kirbychris This is fixed. Can you close this issue? (Sorry to bother you about issue tracking here)

I don't see any option for me to close this.

**Comment by kirbychris** [comment]
Oh weird - yeah, I thought others could close issues. When I merge PRs in the future, I'll try to remember to close the affiliated issue(s).
