### ISSUE TITLE
Netperf ftp links are not working

### ISSUE THREAD

**Issue by aanm** [HewlettPackard/netperf#2]
The ftp links to download netperf are not working:

ftp://ftp.cup.hp.com/dist/networking/benchmarks/netperf/

**Comment by kirbychris** [comment]
The FTP site has been shut down. The downloads are now available here: https://github.com/HewlettPackard/netperf/releases/tag/netperf-2.7.0.

**Comment by q2dg** [comment]
README should be modified!!
