### ISSUE TITLE
netperf compile error with "--enable-intervals=yes"

### ISSUE THREAD

**Issue by quanwenli** [HewlettPackard/netperf#59]
Netperf compile error with " --enable-intervals=yes"

/usr/bin/ld: nettest_omni.o:(.bss+0x0): multiple definition of `interval_count'; nettest_bsd.o:(.bss+0x60): first defined here
/usr/bin/ld: nettest_omni.o:(.bss+0x20): multiple definition of `signal_set'; nettest_bsd.o:(.bss+0x80): first defined here

**Comment by lele121314** [comment]
1、make clean

2、make CFLAGS=-fcommon （for gcc 10）

**Comment by 79rpm** [comment]
I have a similar issue with Raspbian. Make sure you install textinfo so makeinfo is available; otherwise the make CLFAGS=-fcommon will also fail!

 $ uname -a
Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux

**Comment by quanwenli** [comment]
> 1、make clean
> 
> 2、make CFLAGS=-fcommon （for gcc 10）

thanks for your information, it fixs the issue on my system.

**Comment by quanwenli** [comment]
> I have a similar issue with Raspbian. Make sure you install textinfo so makeinfo is available; otherwise the make CLFAGS=-fcommon will also fail!

thanks for your information, on rhel, do not need textinfo. 
> 
> $ uname -a Linux raspberrypi 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux
